name: sovchilar
description: Dating application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  http: any
  dio: ^5.4.0
  path: ^1.8.3
  shimmer: ^3.0.0
  logger: ^2.0.2+1
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.0

  lottie: ^2.2.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.14
  in_date_utils: ^1.2.0+2
  email_validator: ^2.1.17
  permission_handler: ^11.0.1
  flutter_multi_formatter: ^2.11.16

  flutter_bloc: ^8.1.3

  get_it: ^7.6.4
  injectable: ^2.3.2
  injectable_generator: ^2.4.1

  auto_route: ^7.8.4

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  path_provider: ^2.1.1

  intl: any
  animate_do: ^3.0.2
  flutter_secure_storage: ^9.0.0

  freezed: ^2.4.5
  freezed_annotation: ^2.4.1

  json_annotation: ^4.8.1
  equatable: ^2.0.5

  easy_localization: ^3.0.3
  easy_localization_loader: ^2.0.0

  import_sorter: ^4.6.0
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/icons/

    - assets/translations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 700
  
